version: "3.7"
services:
  postgres:
    image: postgres:15
    container_name: flex-sheet-architecture-test-db
    networks:
      - api
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.example
networks:
  api:
volumes:
  pgdata:
